apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: jwtpolicies.appid.cloud.ibm.com
spec:
  group: appid.cloud.ibm.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  version: v1
  names:
    plural: jwtpolicies
    singular: jwtpolicy
    kind: JwtPolicy
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - jwksUrl
            - target
          properties:
            jwksUrl:
              type: string
              pattern: '^(?:http(s)?:\/\/)?((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(\:\d+)?(\/[-a-z\d%_.~+]*)*(\?[;&a-z\d%_.~+=-]*)?(\#[-a-z\d_]*)?$'
            target:
              type: array
              items:
                type: object
                properties:
                  serviceName:
                    type: string
                    minLength: 1
                  paths:
                    type: array
                    items:
                      type: string
                      minLength: 1
                required:
                  - serviceName
