/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "ibmcloudappid/adapter/pkg/apis/policies/v1"
	scheme "ibmcloudappid/adapter/pkg/client/clientset/versioned/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OidcClientsGetter has a method to return a OidcClientInterface.
// A group's client should implement this interface.
type OidcClientsGetter interface {
	OidcClients(namespace string) OidcClientInterface
}

// OidcClientInterface has methods to work with OidcClient resources.
type OidcClientInterface interface {
	Create(*v1.OidcClient) (*v1.OidcClient, error)
	Update(*v1.OidcClient) (*v1.OidcClient, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.OidcClient, error)
	List(opts metav1.ListOptions) (*v1.OidcClientList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.OidcClient, err error)
	OidcClientExpansion
}

// oidcClients implements OidcClientInterface
type oidcClients struct {
	client rest.Interface
	ns     string
}

// newOidcClients returns a OidcClients
func newOidcClients(c *AppidV1Client, namespace string) *oidcClients {
	return &oidcClients{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the oidcClient, and returns the corresponding oidcClient object, and an error if there is any.
func (c *oidcClients) Get(name string, options metav1.GetOptions) (result *v1.OidcClient, err error) {
	result = &v1.OidcClient{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("oidcclients").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OidcClients that match those selectors.
func (c *oidcClients) List(opts metav1.ListOptions) (result *v1.OidcClientList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.OidcClientList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("oidcclients").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested oidcClients.
func (c *oidcClients) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("oidcclients").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a oidcClient and creates it.  Returns the server's representation of the oidcClient, and an error, if there is any.
func (c *oidcClients) Create(oidcClient *v1.OidcClient) (result *v1.OidcClient, err error) {
	result = &v1.OidcClient{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("oidcclients").
		Body(oidcClient).
		Do().
		Into(result)
	return
}

// Update takes the representation of a oidcClient and updates it. Returns the server's representation of the oidcClient, and an error, if there is any.
func (c *oidcClients) Update(oidcClient *v1.OidcClient) (result *v1.OidcClient, err error) {
	result = &v1.OidcClient{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("oidcclients").
		Name(oidcClient.Name).
		Body(oidcClient).
		Do().
		Into(result)
	return
}

// Delete takes name of the oidcClient and deletes it. Returns an error if one occurs.
func (c *oidcClients) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("oidcclients").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *oidcClients) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("oidcclients").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched oidcClient.
func (c *oidcClients) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.OidcClient, err error) {
	result = &v1.OidcClient{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("oidcclients").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
