/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	v1 "ibmcloudappid/pkg/apis/policies/v1"
	scheme "ibmcloudappid/pkg/client/clientset/versioned/scheme"
	"time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// OidcPoliciesGetter has a method to return a OidcPolicyInterface.
// A group's client should implement this interface.
type OidcPoliciesGetter interface {
	OidcPolicies(namespace string) OidcPolicyInterface
}

// OidcPolicyInterface has methods to work with OidcPolicy resources.
type OidcPolicyInterface interface {
	Create(*v1.OidcPolicy) (*v1.OidcPolicy, error)
	Update(*v1.OidcPolicy) (*v1.OidcPolicy, error)
	Delete(name string, options *metav1.DeleteOptions) error
	DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error
	Get(name string, options metav1.GetOptions) (*v1.OidcPolicy, error)
	List(opts metav1.ListOptions) (*v1.OidcPolicyList, error)
	Watch(opts metav1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.OidcPolicy, err error)
	OidcPolicyExpansion
}

// oidcPolicies implements OidcPolicyInterface
type oidcPolicies struct {
	client rest.Interface
	ns     string
}

// newOidcPolicies returns a OidcPolicies
func newOidcPolicies(c *AppidV1Client, namespace string) *oidcPolicies {
	return &oidcPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the oidcPolicy, and returns the corresponding oidcPolicy object, and an error if there is any.
func (c *oidcPolicies) Get(name string, options metav1.GetOptions) (result *v1.OidcPolicy, err error) {
	result = &v1.OidcPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("oidcpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of OidcPolicies that match those selectors.
func (c *oidcPolicies) List(opts metav1.ListOptions) (result *v1.OidcPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.OidcPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("oidcpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested oidcPolicies.
func (c *oidcPolicies) Watch(opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("oidcpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a oidcPolicy and creates it.  Returns the server's representation of the oidcPolicy, and an error, if there is any.
func (c *oidcPolicies) Create(oidcPolicy *v1.OidcPolicy) (result *v1.OidcPolicy, err error) {
	result = &v1.OidcPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("oidcpolicies").
		Body(oidcPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a oidcPolicy and updates it. Returns the server's representation of the oidcPolicy, and an error, if there is any.
func (c *oidcPolicies) Update(oidcPolicy *v1.OidcPolicy) (result *v1.OidcPolicy, err error) {
	result = &v1.OidcPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("oidcpolicies").
		Name(oidcPolicy.Name).
		Body(oidcPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the oidcPolicy and deletes it. Returns an error if one occurs.
func (c *oidcPolicies) Delete(name string, options *metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("oidcpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *oidcPolicies) DeleteCollection(options *metav1.DeleteOptions, listOptions metav1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("oidcpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched oidcPolicy.
func (c *oidcPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1.OidcPolicy, err error) {
	result = &v1.OidcPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("oidcpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
