/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	policiesv1 "github.com/ibm-cloud-security/policy-enforcer-mixer-adapter/adapter/pkg/apis/policies/v1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeOidcClients implements OidcClientInterface
type FakeOidcClients struct {
	Fake *FakeAppidV1
	ns   string
}

var oidcclientsResource = schema.GroupVersionResource{Group: "appid.cloud.ibm.com", Version: "v1", Resource: "oidcclients"}

var oidcclientsKind = schema.GroupVersionKind{Group: "appid.cloud.ibm.com", Version: "v1", Kind: "OidcClient"}

// Get takes name of the oidcClient, and returns the corresponding oidcClient object, and an error if there is any.
func (c *FakeOidcClients) Get(name string, options v1.GetOptions) (result *policiesv1.OidcClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(oidcclientsResource, c.ns, name), &policiesv1.OidcClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*policiesv1.OidcClient), err
}

// List takes label and field selectors, and returns the list of OidcClients that match those selectors.
func (c *FakeOidcClients) List(opts v1.ListOptions) (result *policiesv1.OidcClientList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(oidcclientsResource, oidcclientsKind, c.ns, opts), &policiesv1.OidcClientList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &policiesv1.OidcClientList{ListMeta: obj.(*policiesv1.OidcClientList).ListMeta}
	for _, item := range obj.(*policiesv1.OidcClientList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested oidcClients.
func (c *FakeOidcClients) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(oidcclientsResource, c.ns, opts))

}

// Create takes the representation of a oidcClient and creates it.  Returns the server's representation of the oidcClient, and an error, if there is any.
func (c *FakeOidcClients) Create(oidcClient *policiesv1.OidcClient) (result *policiesv1.OidcClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(oidcclientsResource, c.ns, oidcClient), &policiesv1.OidcClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*policiesv1.OidcClient), err
}

// Update takes the representation of a oidcClient and updates it. Returns the server's representation of the oidcClient, and an error, if there is any.
func (c *FakeOidcClients) Update(oidcClient *policiesv1.OidcClient) (result *policiesv1.OidcClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(oidcclientsResource, c.ns, oidcClient), &policiesv1.OidcClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*policiesv1.OidcClient), err
}

// Delete takes name of the oidcClient and deletes it. Returns an error if one occurs.
func (c *FakeOidcClients) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(oidcclientsResource, c.ns, name), &policiesv1.OidcClient{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeOidcClients) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(oidcclientsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &policiesv1.OidcClientList{})
	return err
}

// Patch applies the patch and returns the patched oidcClient.
func (c *FakeOidcClients) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *policiesv1.OidcClient, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(oidcclientsResource, c.ns, name, pt, data, subresources...), &policiesv1.OidcClient{})

	if obj == nil {
		return nil, err
	}
	return obj.(*policiesv1.OidcClient), err
}
