language: go

branches:
  only:
    - master
    - development
    - /\d+\.\d+\.\d+/

go:
  - 1.12.x
  - release
  - tip

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
    - go: tip
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true

git:
  depth: 1

install: true

before_script:
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run       # run a bunch of code checkers/linters in parallel
  - go test -v -race ./...  # Run all the tests with the race detector enable

notifications:
  email:
    on_success: always
    on_failure: always

