
[[constraint]]
  name = "github.com/dgrijalva/jwt-go"
  version = "3.2.0"

[[constraint]]
  name = "github.com/gogo/googleapis"
  branch = "master"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.2.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.13.0"

[[constraint]]
  branch = "release-1.1"
  name = "istio.io/api"

[[constraint]]
  name = "istio.io/istio"
  version = "~1.1.0"

[[constraint]]
  branch = "release-1.14"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "11.0.0"

[[constraint]]
  name = "golang.org/x/sync"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "^1.1.1"

[prune]
  go-tests = true
  unused-packages = true
