# instance for authorization template
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: instance-{{ .Values.appName }}
  namespace: istio-system
spec:
  template: authnz
  params:
    target:
      path: request.url_path | "/"
      method: request.method | "get"
      service: destination.service.name | ""
      namespace: destination.service.namespace | "default"
    request:
      scheme: request.scheme | ""
      host: request.host | ""
      path: request.url_path | ""
      headers:
        cookies: request.headers["cookie"] | ""
        authorization: request.headers["authorization"] | ""
      params:
        code: request.query_params["code"] | ""
        error: request.query_params["error"] | ""

