# instance for authorization template
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: instance-{{ .Values.appName }}
  namespace: istio-system
spec:
  template: authorization
  params:
    subject:
      properties:
        authorization_header: request.headers["authorization"]
    action:
      path: request.path | "/"
      method: request.method | "get"
      service: destination.service.host | ""
      namespace: destination.service.namespace | "default:wtf"