# instance for authorization template
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: instance-appid-api
  namespace: istio-system
spec:
  template: authorization
  params:
    subject:
      properties:
        authorization_header:  request.headers["authorization"]
        destination_service_host: destination.service.host | ""