apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: oidcclients.appid.cloud.ibm.com
spec:
  group: appid.cloud.ibm.com
  versions:
    - name: v1
      served: true
      storage: true
  scope: Namespaced
  version: v1
  names:
    plural: oidcclients
    singular: oidcclient
    kind: OidcClient
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - oidcClientName
            - clientId
            - discoveryUrl
          properties:
            authMethod:
              type: string
              enum:
                - client_secret_basic
                - client_secret_post
            oidcClientName:
              type: string
              minLength: 1
            clientId:
              type: string
              minLength: 1
            discoveryUrl:
              type: string
              pattern: '^(?:http(s)?:\/\/)?((([a-z\d]([a-z\d-]*[a-z\d])*)\.)+[a-z]{2,}|((\d{1,3}\.){3}\d{1,3}))(\:\d+)?(\/[-a-z\d%_.~+]*)*(\?[;&a-z\d%_.~+=-]*)?(\#[-a-z\d_]*)?$'
            clientSecret:
              type: string
              minLength: 1
            clientSecretRef:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                key:
                  type: string
                  minLength: 1
              required:
                - name
                - key
