# rule to dispatch the app ID adapter handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: rule-{{ .Values.appName }}
  namespace: istio-system
spec:
  actions:
    - handler: handler-{{ .Values.appName }}.istio-system
      instances:
        - instance-{{ .Values.appName }}
      name: a1
  responseHeaderOperations:
    - name: Set-Cookie
      values: [ a1.output.id_token_cookie, a1.output.refresh_token_cookie, a1.output.access_token_cookie ]
      operation: APPEND
