apiVersion: v1
kind: Service
metadata:
  name: svc-{{ .Values.appName }}
  namespace: istio-system
  labels:
    app: {{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.appName }}
---