/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1

// JwtPolicyListerExpansion allows custom methods to be added to
// JwtPolicyLister.
type JwtPolicyListerExpansion interface{}

// JwtPolicyNamespaceListerExpansion allows custom methods to be added to
// JwtPolicyNamespaceLister.
type JwtPolicyNamespaceListerExpansion interface{}

// OidcClientListerExpansion allows custom methods to be added to
// OidcClientLister.
type OidcClientListerExpansion interface{}

// OidcClientNamespaceListerExpansion allows custom methods to be added to
// OidcClientNamespaceLister.
type OidcClientNamespaceListerExpansion interface{}

// OidcPolicyListerExpansion allows custom methods to be added to
// OidcPolicyLister.
type OidcPolicyListerExpansion interface{}

// OidcPolicyNamespaceListerExpansion allows custom methods to be added to
// OidcPolicyNamespaceLister.
type OidcPolicyNamespaceListerExpansion interface{}
