/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	time "time"

	policiesv1 "istio.io/istio/mixer/adapter/ibmcloudappid/pkg/apis/policies/v1"
	versioned "istio.io/istio/mixer/adapter/ibmcloudappid/pkg/client/clientset/versioned"
	internalinterfaces "istio.io/istio/mixer/adapter/ibmcloudappid/pkg/client/informers/externalversions/internalinterfaces"
	v1 "istio.io/istio/mixer/adapter/ibmcloudappid/pkg/client/listers/policies/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// JwtPolicyInformer provides access to a shared informer and lister for
// JwtPolicies.
type JwtPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.JwtPolicyLister
}

type jwtPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewJwtPolicyInformer constructs a new informer for JwtPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewJwtPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredJwtPolicyInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredJwtPolicyInformer constructs a new informer for JwtPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredJwtPolicyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppidV1().JwtPolicies(namespace).List(options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AppidV1().JwtPolicies(namespace).Watch(options)
			},
		},
		&policiesv1.JwtPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *jwtPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredJwtPolicyInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *jwtPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&policiesv1.JwtPolicy{}, f.defaultInformer)
}

func (f *jwtPolicyInformer) Lister() v1.JwtPolicyLister {
	return v1.NewJwtPolicyLister(f.Informer().GetIndexer())
}
