apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gw-sample-app
  namespace: sample-app
spec:
  selector:
    istio: ingressgateway # use Istio default gateway implementation
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: vsvc-sample-app
  namespace: sample-app
spec:
  hosts:
    - "*"
  gateways:
    - gw-sample-app
  http:
    - match:
        - uri:
            prefix: /api
        - uri:
            prefix: /
      route:
        - destination:
            port:
              number: 8000
            host: svc-sample-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dpl-sample-app
  namespace: sample-app
  labels:
    app: sample-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: ishangulhane/demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-sample-app
  namespace: sample-app
  labels:
    app: sample-app
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      protocol: TCP
  selector:
    app: sample-app
