apiVersion: "security.cloud.ibm.com/v1"
kind:       Policy
metadata:
  name:      samplepolicy
  namespace: sample-app
spec:
  targets:
    -
      serviceName: svc-sample-app
      paths:
        - exact: /web/home
          method: ALL
          policies:
            - policyType: oidc
              config: sampleoidcconfig
              rules:
                - claim: scope
                  match: ALL
                  source: access_token
                  values:
                    - appid_default
                    - openid
                - claim: amr
                  match: ANY
                  source: id_token
                  values:
                    - cloud_directory
                    - google

        - exact: /web/user
          method: GET
          policies:
            - policyType: oidc
              config: sampleoidcconfigwithsecretref
              redirectUri: https://github.com/ibm-cloud-security/policy-enforcer-mixer-adapter
        - prefix: /
          method: ALL
          policies:
            -
              policyType: jwt
              config: samplejwtconfig