apiVersion: "appid.cloud.ibm.com/v1"
kind: JwtPolicy
metadata:
  name: samplejwtpolicy
  namespace: demo-backend-namespace
spec:
  jwksUrl: https://appid-oauth.stage1.eu-gb.bluemix.net/oauth/v4/71b34890-a94f-4ef2-a4b6-ce094aa68092/publickeys

  target:
    - serviceName: svc-demo-backend
      paths:
        - /
